name: Generic zig build
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!zig-develop*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: elerch/setup-zig@v3
        with:
          version: 0.13.0
      - uses: elerch/zig-action-cache@v1.1.6
      - name: Install system dependencies (Github)
        if: env.GITEA_ACTIONS != 'true'
        run: |
          sudo apt-get update 
          sudo apt-get install fonts-hack # imagemagick (container has imagemagick, but version 6)
          curl -LOs https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.1-31.tar.gz
          tar xzf 7.1.1-31.tar.gz
          cd ImageMagick-7.1.1-31/
          ./configure && sudo make install && sudo ldconfig /usr/local/lib
          cd ..
      - name: Install system dependencies (Gitea)
        if: env.GITEA_ACTIONS == 'true'
        run: |
          apt-get update 
          apt-get install fonts-hack # imagemagick (container has imagemagick, but version 6)
          curl -LOs https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.1-31.tar.gz
          tar xzf 7.1.1-31.tar.gz
          cd ImageMagick-7.1.1-31/
          ./configure && make install && ldconfig /usr/local/lib
          cd ..
      - name: Build project
        run: zig build --summary all
      - name: Run tests
        run: zig build test --summary all
      - name: Notify
        uses: elerch/action-notify-ntfy@v2.github
        if: always() && env.GITEA_ACTIONS == 'true'
        with:
          host: ${{ secrets.NTFY_HOST }}
          topic: ${{ secrets.NTFY_TOPIC }}
          status: ${{ job.status }}
          user: ${{ secrets.NTFY_USER }}
          password: ${{ secrets.NTFY_PASSWORD }}
